spring:
  profiles.active: ${profile}
---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/bloggito
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  contextPath: /api
